@baseUrl = http://localhost:3000/api

@resourceName = products

# @name getAllList
GET {{baseUrl}}/{{resourceName}}

###

# @name getItemById
GET {{baseUrl}}/{{resourceName}}/826f8b0e-a8f0-4415-991c-4579c29be70c

###

# @name filterItem
GET {{baseUrl}}/{{resourceName}}?price_gte=300

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=2

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc

###

# @name relationship
GET {{baseUrl}}/{{resourceName}}?_expand=category

###

# @name addNewItem
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "name": "Macbook",
  "color": "mint green",
  "price": 800,
  "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
  "thumbnailUrl": "https://loremflickr.com/400/400",
  "categoryId": "07644abb-9c2d-4985-beb0-e935f0cee349"
}

###

# @name updateItem
PATCH  {{baseUrl}}/{{resourceName}}/c56c7e2d-19ca-4be7-b561-269812d0aa75
Content-Type: application/json

{
  "name": "Laptop"
}

###

# @name deleteItem
DELETE   {{baseUrl}}/{{resourceName}}/7XLsA3-